language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

script:
  - npm run docs:build

after_script:
  - cd dist
  - git init
  - git config user.name "kingDuiDui"
  - git config user.email "m18508218948@163.com"
  - git add .
  - git commit -m 'deploy'
  - git push -f ${GH_token}@${GH_REF} master:master
# E: Build LifeCycle

branches:
  only:
    - blog
env:
 global:
   - GH_REF: github.com:kingDuiDui/my-blog.git